version: '3.9'

services:
  mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      ports:
       - 2717:27017
      volumes: 
        - mongo_db:/data/db
  
  api:
    build: .
    ports:
      - 8080:8080
    environment:
        PORT: 8080
        MONGODB_URI: mongodb://mongo_db:27017/my_database
        NODE_ENV: development

        CORS_ORIGIN: http://localhost:3000
        BACKEND_HOST_URL: http://localhost:8081

        ACCESS_TOKEN_SECRET: ved$12@Padal
        ACCESS_TOKEN_EXPIRY: 1d
        REFRESH_TOKEN_SECRET: Ved@789
        REFRESH_TOKEN_EXPIRY: 10d

        RESEND_API_KEY: re_2N4k1p8H_GZbPpSLDchhCyHs7LcMNtzrT

        FORGOT_PASSWORD_REDIRECT_URL: http://localhost:3000/forgot-password
    
    depends_on:
     - mongo_db

volumes:
   mongo_db: {}
